server:
  port: 8080

spring:
  application:
    name: "Drones Rest API"
  profiles:
    active:
      - "h2"

springdoc:
  swagger-ui:
    path: /docs


scheduler:
  audit-interval: 60000
  drone-state-updater: 1000
